### PR TITLE
default deposit_date if recvd_initial_deposition_date is missing and Populate source_pae_url

### PR DESCRIPTION
**Pull request by aliciaaevans**
Due to changes in the way the ModelArchive mmCIF files are retrieved, the `pdbx_database_status` category now exists, but the `pdbx_database_status.recvd_initial_deposition_date` field is not populated when the comp model core data loading occurs. The existing code checked if `pdbx_database_status` did not exist and if it was a MA entry and added `pdbx_database_status`, setting `recvd_initial_deposition_date` to `?`.

This change returns a default value of `?` if `recvd_initial_deposition_date` is null or missing. The end result of this change defaulting that value to `?` is that the deposit_date is not included in the DB, but that's the way it is in prod for the existing MA entries.

### CODE REVIEW

**Review by brindakv — APPROVED** [review]
Thanks @aliciaaevans. Looks good to me.

**Review by piehld — APPROVED** [review]
Looks good to me too, thanks!

**Review by piehld — CHANGES_REQUESTED** [review]
Oh sorry, actually, there are some other changes you need to make. Since this is a package update, you'll need to increment the version number of the file `rcsb/utils/dictionary/__init__.py` as well as add a new line in the HISTORY.txt file with a description of the change.

**Review by piehld — APPROVED** [review]
Thanks!

**Pull request merged**
