### PR TITLE
RO-3814: V1.08 Update population of rcsb_entity_source_organism.provenance_source

### PR DESCRIPTION
**Pull request by piehld**
Jira ticket: https://rcsbpdb.atlassian.net/browse/RO-3814

First, in `DictMethodCompModelHelper.py`:
- If CSM and `ma_target_ref_db_details.db_name` is "UNP" -> set `entity_src_nat.rcsb_provenance_source` to UniProt
- If CSM and `ma_target_ref_db_details.db_name` is "Other" -> set `entity_src_nat.rcsb_provenance_source` to NCBI

.

Then, in `DictMethodEntityHelper.py`:
- If Experimental structure:
  - set `_rcsb_entity_source_organism.provenance_source` to "Primary Data"
- Else if CSM and `entity_src_nat.rcsb_provenance_source` exists:
  - set `_rcsb_entity_source_organism.provenance_source` to the value of `entity_src_nat.rcsb_provenance_source` (i.e., UniProt or NCBI)

.

Also addresses: https://rcsbpdb.atlassian.net/browse/RO-3840

### CODE REVIEW

**Review by brindakv — APPROVED** [review]
Thanks @piehld. Looks good.

**Review by brindakv — CHANGES_REQUESTED** [review]
@piehld In DictMethodCompModelHelper, `entity_src_nat` is overwritten by information in `ma_target_ref_db_details`. I suggest to modify this and retain information from `entity_src_nat` if all the required attributes are populated. In such cases, `provenance_source` can be `Primary Data` as in PDB structures.

**Comment by piehld** [comment]
@brindakv Thanks for the review and feedback. I've adjusted the code to handle cases in such a manner. Can you please re-review?

**Review by brindakv — APPROVED** [review]
@piehld Thanks for addressing this. Looks good to me.

**Pull request merged**
