### PR TITLE
V0.86-V0.96 Features: Support loading of computed structure models

### PR DESCRIPTION
**Pull request by piehld**
Merging a series of updates to the codebase for supporting the loading of computed structure models.

### CODE REVIEW

**Comment by piehld** [comment]
FYI @brindakv, I'm not necessarily looking to merge this right away, but just trying to get things ready so we can do so easily when the time comes.

**Comment by piehld** [comment]
@brindakv FYI I noticed there was an issue with indentation, just pushed a commit here to fix it (https://github.com/rcsb/py-rcsb_utils_dictionary/pull/44/commits/7218213524b656e7cafbbf2f2b01252be77895c3)

**Comment by brindakv** [comment]
> @brindakv FYI I noticed there was an issue with indentation, just pushed a commit here to fix it ([7218213](https://github.com/rcsb/py-rcsb_utils_dictionary/commit/7218213524b656e7cafbbf2f2b01252be77895c3))

Thanks @piehld

**Review by brindakv — APPROVED** [review]
@piehld Looks good to me. Thanks.

**Pull request merged**
