### PR TITLE
RO-3139

### PR DESCRIPTION
**Pull request by brindakv**
This commit fixes `_rcsb_assembly_info.atom_count` not being populated for certain NMR entries.

### CODE REVIEW

**Review by piehld — APPROVED** [review]
Looks great, thanks! Just curious, what was the reason for moving `getRepresentativeModels` from DictMethodEntryHelper to DictMethodCommonUtils?

**Comment by brindakv** [comment]
> Looks great, thanks! Just curious, what was the reason for moving `getRepresentativeModels` from DictMethodEntryHelper to DictMethodCommonUtils?

I moved it so that the method can be used in `DictMethodAssemblyHelper`. Avoids duplication.

**Comment by piehld** [comment]
OK that makes sense, thanks for letting me know. Kind of strange that it's failing though. Looks like it's taking a long time to run as well, like what I've been experiencing. You might try just re-running the failed jobs (there's an option for that when you go to the pipeline page: https://dev.azure.com/rcsb/RCSB%20PDB%20Python%20Projects/_build/results?buildId=4609&view=results)

**Comment by piehld** [comment]
@brindakv I figured out what the issue was for both this dictionary pipeline as well as the py-rcsb_db pipeline. They were both restoring the neighbor-interactions data from Git stash (https://github.com/rcsb/py-rcsb_exdb_assets_stash/tree/testing/stash/neighbor-interactions), which I had regenerated and updated last week. However, apparently the "normal" data content on the `testing` branch of `py-rcsb_exdb_assets_stash` is for only 50 entries, not the entire archive. So, when I had updated it to contain the data for the entire archive, that slowed all the Azure builds down and apparently caused them to crash.

**Comment by brindakv** [comment]
> @brindakv I figured out what the issue was for both this dictionary pipeline as well as the py-rcsb_db pipeline. They were both restoring the neighbor-interactions data from Git stash (https://github.com/rcsb/py-rcsb_exdb_assets_stash/tree/testing/stash/neighbor-interactions), which I had fully regenerated and updated last week. However, apparently the "normal" neighbor-interactions data content on the `testing` branch of `py-rcsb_exdb_assets_stash` is for only 50 entries, not the entire archive. So, when I had updated it to contain the data for the entire archive, that slowed all the Azure builds down and apparently caused them to crash.
> 
> I just fixed this by reverting my last commit on `py-rcsb_exdb_assets_stash`.

Thank you, @piehld. I merge the pull request.

**Pull request merged**
